# Gitleaks Configuration - Custom Rules
# This config makes Gitleaks MORE STRICT than GitHub Push Protection

title = "Gitleaks Custom Config for CICD Demo"

# Custom rules for detecting secrets
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey)\s*[=:]\s*["\']?[a-zA-Z0-9_-]{20,}["\']?'''
keywords = ["api_key", "apikey", "API_KEY"]

[[rules]]
id = "generic-password"
description = "Generic Password"
regex = '''(?i)(password|pwd|pass)\s*[=:]\s*["\']?[a-zA-Z0-9_@#$%^&*()-+=]{8,}["\']?'''
keywords = ["password", "PASSWORD", "pwd"]

[[rules]]
id = "generic-secret-key"
description = "Generic Secret Key"
regex = '''(?i)(secret[_-]?key|secretkey)\s*[=:]\s*["\']?[a-zA-Z0-9_-]{16,}["\']?'''
keywords = ["secret_key", "secretkey", "SECRET_KEY"]

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[a-zA-Z0-9_-]*\.eyJ[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*'''

[[rules]]
id = "sk-pattern"
description = "SK Pattern (OpenAI/Stripe like)"
regex = '''sk-[a-zA-Z0-9]{20,}'''

[[rules]]
id = "database-credentials"
description = "Database Credentials"
regex = '''(?i)(db[_-]?password|database[_-]?password)\s*[=:]\s*["\']?[a-zA-Z0-9_@#$%^&*()-+=]{6,}["\']?'''

# Allowlist paths (files to skip scanning)
[allowlist]
paths = [
    '''^\.git/''',
    '''^node_modules/'''
]

# Global allowlist (patterns to ignore)
regexes = [
    '''password\s*=\s*["']?(example|test|demo|placeholder)["']?''',  # Allow example passwords
]
