# Gitleaks Configuration Options
# Choose your security level:

# OPTION 1: Production-ready (Default Gitleaks rules)
# - Catches real service secrets (AWS, GitHub, Stripe)
# - Ignores obvious demo/placeholder values
# - Minimal false positives

# OPTION 2: Strict mode (Everything blocked)
# - Catches any hardcoded values
# - Many false positives
# - Good for demo/learning

# Current: Using DEFAULT RULES (no custom rules defined)

[allowlist]
paths = [
    '''^\.git/''',
    '''^node_modules/''',
    '''^demo-secrets\.txt$''',
    '''^demo-scripts\.sh$''',
    '''^branch-protection-setup\.md$'''
]

# Uncomment below for STRICT MODE:
# [[rules]]
# id = "any-password"
# description = "Any Password Field"
# regex = '''(?i)(password|pwd)\s*[=:]\s*["\'][^"\'\s]{3,}["\']'''
#
# [[rules]]
# id = "any-username"
# description = "Any Username Field"
# regex = '''(?i)(username|user)\s*[=:]\s*["\'][^"\'\s]{3,}["\']'''
#
# [[rules]]
# id = "any-apikey"
# description = "Any API Key Field"
# regex = '''(?i)(apikey|api_key)\s*[=:]\s*["\'][^"\'\s]{3,}["\']'''
